### PR TITLE
Speed up DRW call

### PR DESCRIPTION
**Pull request by pamidur**
By 2 times!
From
```c#
00:00:01.0852349 DBG interperter
00:00:00.9618549 Interperter
00:00:00.0192523 JIT
```
To
```c#
00:00:01.0792545 DBG interperter
00:00:00.9526507 Interperter
00:00:00.0081705 JIT
```

Done by aligning sprite before apply and apply to two whole bytes at ones, like this
```
00xxxxxx xx000000
11111111 00000000
```
where xxxxxxxx - byte of sprite.

note: we can speed up it even more if realign vmem to be vertically aligned, then make two Vector<byte> with sprite patch for right and left column (in case x % 8 == 0 only one column) and apply it with Vector.Xor. This operation in SIMD accelerated.

### CODE REVIEW

**Comment by exelix11** [comment]
Great job again :)
> note: we can speed up it even more if realign vmem to be vertically aligned, then make two Vertorwith sprite patch for right and left column (in case x % 8 == 0 only one column) and apply it with Verctor.Xor. This operation in SIMD accelerated.

If you want to that's fine by me, my goal was to have the same implementation in C and C# for a fair comparison so it doesn't matter if we don't squeeze the draw function to the maximum performance.

**Comment by pamidur** [comment]
Yeah, I got, it just was fun.
However I believe to have a fair comparison among c++ vs c# vs c# jit , you'd want to include only those operations that are in fact have something to do with _jit vs interpreter_, and draw call is not one of them.

upd. So for fair comparison I'd rather ignore draw call at all by faking it.

**Comment by pamidur** [comment]
Sorry to disturb you @exelix11 , I thought you might consider my tests and conclusions.
So what I did:
- stubbed DRAW method for both c# and c++, leaving it empty
- made code run run 50000 for benchmark

Results
```c#
8.724984s DBG interperter
8.402784s Interperter
0.011406s JIT
0.290313s C++
```

Thus my conclusion is if we compare only interpreting/jitting code and not syscalls implementations, then c# JIT (in fact managed JIT) is far superior than c++ interpret

**Comment by exelix11** [comment]
Good point, may actually make another branch just for that kind of benchmark.
I like to think that having an actual implementation is better cause it gives you a real life comparison for emulators, accounting for the inevitable speed difference between native and .net

Will merge this PR in a bit, just finished making a github action that automatically performs the release mode benchmarks on push, trying to find a way of nicely show it without having to open the logs.

**Comment by pamidur** [comment]
Although I'm not arguing that c# is inevitably slower, but it seems that the real difference varies a lot depending on algorithm.

On the benchmark results point: maybe it's worth to parse it out of console output and put on to release/wiki page, or updating readme.md directly somehow avoiding recursion :)

**Comment by exelix11** [comment]
> Although I'm not arguing that c# is inevitably slower, but it seems that the real difference varies a lot depending on algorithm.

That's the point of having the same algorithm in both versions, so each one gets optimized by the respective compiler and has its weight counted in the benchmark.

> On the benchmark results point: maybe it's worth to parse it out of console output and put on to release/wiki page, or updating readme.md directly somehow avoiding recursion :)

It seems that it's possible to add files via the actions job but i'm very new at this so not sure if i can manage it, may just end up adding the output of the script as a .txt build artifact.
Btw merged the action here to test and it does work:
```
00:00:01.4834682 C# DBG interperter
00:00:01.3914952 C# Interperter
00:00:00.0106932 C# JIT
00:00:00.0348870 C interpreter
```

**Comment by exelix11** [comment]
Merged and updated the readme with your results :+1:
If you have any other idea feel free to contact me here or on reddit.
As soon as i get over with other projects and have some free time will try to put togheter an x86 JIT version

**Pull request merged**
